// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Webapi__Canvas__Canvas2d from "bs-webapi/src/Webapi/Canvas/Webapi__Canvas__Canvas2d.bs.js";

function renderCanvas(element, context) {
  var width = element.width;
  var height = element.height;
  var centerX = width / 2.0;
  Webapi__Canvas__Canvas2d.setFillStyle(context, /* String */0, "white");
  context.fillRect(centerX, 0.0, width / 2.0, height / 2.0);
  
}

function Timeline(Props) {
  var canvasRef = React.useRef(null);
  React.useEffect((function () {
          Belt_Option.forEach(Caml_option.nullable_to_opt(canvasRef.current), (function (element) {
                  var context = element.getContext("2d");
                  return renderCanvas(element, context);
                }));
          
        }), []);
  return React.createElement("canvas", {
              ref: canvasRef,
              height: "400px",
              width: "calc(100vw)"
            });
}

var Canvas;

var Canvas2d;

var make = Timeline;

export {
  Canvas ,
  Canvas2d ,
  renderCanvas ,
  make ,
  
}
/* react Not a pure module */
