// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as EditorContext from "../../EditorContext.bs.js";
import * as SeekBarCanvas from "./SeekBarCanvas.bs.js";
import * as SceneMapCanvas from "./SceneMapCanvas.bs.js";

function Timeline(Props) {
  var sectionSize = Props.sectionSize;
  var editorContext = EditorContext.useEditorContext(undefined);
  var size = React.useMemo((function () {
          var scale = window.devicePixelRatio;
          var maxSceneWidth = sectionSize.width - 64;
          return {
                  width: sectionSize.width,
                  height: sectionSize.height,
                  scale: scale,
                  scaledWidth: sectionSize.width * scale,
                  scaledHeight: sectionSize.height * scale,
                  maxSceneWidth: maxSceneWidth,
                  frameToPxRatio: maxSceneWidth / editorContext.videoMeta.durationInFrames
                };
        }), [
        sectionSize.height,
        sectionSize.width,
        sectionSize.scale,
        editorContext.videoMeta.durationInFrames
      ]);
  return React.createElement("div", {
              className: "relative"
            }, React.createElement(SceneMapCanvas.make, {
                  size: size
                }), React.createElement(SeekBarCanvas.make, {
                  size: size
                }));
}

var make = Timeline;

export {
  make ,
  
}
/* react Not a pure module */
