// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Range from "rescript/lib/es6/belt_Range.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as EditorContext from "../../EditorContext.bs.js";
import * as Webapi__Canvas__Canvas2d from "bs-webapi/src/Webapi/Canvas/Webapi__Canvas__Canvas2d.bs.js";

function renderRoundedRect(ctx, x, y, width, height, radius, param) {
  ctx.beginPath();
  ctx.moveTo(x + radius, y);
  ctx.arcTo(x + width, y, x + width, y + height, radius);
  ctx.arcTo(x + width, y + height, x, y + height, radius);
  ctx.arcTo(x, y + height, x, y, radius);
  ctx.arcTo(x, y, x + width, y, radius);
  ctx.stroke();
  
}

function clipOverTimeLineElement(ctx, y, width) {
  renderRoundedRect(ctx, 64.0 / 2.0, y, width, 120.0, 8.0, undefined);
  ctx.clip();
  
}

function renderMainScene(ctx, size, editorContext) {
  var maxSceneWidth = size.width - 64.0 * 2;
  var aspectRatio = editorContext.videoMeta.width / editorContext.videoMeta.height;
  var width = 120.0 * aspectRatio;
  clipOverTimeLineElement(ctx, 32.0, maxSceneWidth);
  var maxFramesInScene = Math.floor(maxSceneWidth / width) | 0;
  Belt_Range.forEach(0, maxFramesInScene, (function (i) {
          debugger;
          var svg = Curry._1(editorContext.wasmController.render_frame, BigInt(Math.imul(i, 150)));
          var image = new Image(width, 120.0);
          image.src = "data:image/svg+xml;base64,".concat(window.btoa(svg));
          image.onload = (function (param) {
              ctx.drawImage(image, 64.0 / 2 + i * width, 32, width, 120.0);
              
            });
          
        }));
  
}

function renderScenesPlaceholder(ctx, size, editorContext) {
  var maxSceneWidth = size.width - 64.0 * 2;
  clipOverTimeLineElement(ctx, 32, maxSceneWidth);
  Webapi__Canvas__Canvas2d.setFillStyle(ctx, /* String */0, "#9ca3af");
  ctx.fillRect(64.0 / 2.0, 32.0, maxSceneWidth, 120.0);
  
}

function renderCanvas(element, context) {
  var width = element.width;
  var height = element.height;
  console.log(width, height);
  
}

function Timeline(Props) {
  var sectionSize = Props.sectionSize;
  var canvasRef = React.useRef(null);
  var editorContext = EditorContext.useEditorContext(undefined);
  React.useEffect((function () {
          var match = editorContext.editorState.playState;
          if (match >= 3) {
            Belt_Option.forEach(Caml_option.nullable_to_opt(canvasRef.current), (function (element) {
                    var context = element.getContext("2d");
                    return renderScenesPlaceholder(context, sectionSize, editorContext);
                  }));
          } else {
            Belt_Option.forEach(Caml_option.nullable_to_opt(canvasRef.current), (function (element) {
                    var context = element.getContext("2d");
                    return renderMainScene(context, sectionSize, editorContext);
                  }));
          }
          
        }), []);
  return React.createElement("canvas", {
              ref: canvasRef,
              height: String(sectionSize.height) + "px",
              width: String(sectionSize.width) + "px"
            });
}

var Canvas;

var Canvas2d;

var timeline_margin_x = 64.0;

var scene_height_size = 120.0;

var make = Timeline;

export {
  Canvas ,
  Canvas2d ,
  timeline_margin_x ,
  scene_height_size ,
  renderRoundedRect ,
  clipOverTimeLineElement ,
  renderMainScene ,
  renderScenesPlaceholder ,
  renderCanvas ,
  make ,
  
}
/* react Not a pure module */
