// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Utils from "../../Utils.bs.js";
import * as React from "react";
import * as Belt_Range from "rescript/lib/es6/belt_Range.js";
import * as Caml_int32 from "rescript/lib/es6/caml_int32.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as EditorContext from "../../EditorContext.bs.js";
import * as Webapi__Canvas__Canvas2d from "bs-webapi/src/Webapi/Canvas/Webapi__Canvas__Canvas2d.bs.js";

function calcMaxSceneWidth(size) {
  return size.width - 64.0 * 2;
}

function renderRoundedRect(ctx, x, y, width, height, radius, param) {
  ctx.beginPath();
  ctx.moveTo(x + radius, y);
  ctx.arcTo(x + width, y, x + width, y + height, radius);
  ctx.arcTo(x + width, y + height, x, y + height, radius);
  ctx.arcTo(x, y + height, x, y, radius);
  ctx.arcTo(x, y, x + width, y, radius);
  ctx.stroke();
  
}

function clipOverTimeLineElement(ctx, y, width) {
  renderRoundedRect(ctx, 64.0 / 2.0, y, width, 120.0, 8.0, undefined);
  ctx.clip();
  
}

function renderMainScene(ctx, size, editorContext) {
  var maxSceneWidth = size.width - 64.0 * 2;
  var aspectRatio = editorContext.videoMeta.width / editorContext.videoMeta.height;
  var width = 120.0 * aspectRatio;
  clipOverTimeLineElement(ctx, 64.0, maxSceneWidth);
  var maxFramesInScene = Math.floor(maxSceneWidth / width) | 0;
  var framesBreak = Caml_int32.div(editorContext.videoMeta.durationInFrames, maxFramesInScene);
  Belt_Range.forEach(0, maxFramesInScene, (function (i) {
          console.log(BigInt(Math.imul(i, framesBreak)));
          var svg = Curry._1(editorContext.wasmController.render_frame, BigInt(Math.imul(i, framesBreak)));
          var image = new Image(width, 120.0);
          image.src = "data:image/svg+xml;base64,".concat(window.btoa(svg));
          image.onload = (function (param) {
              ctx.drawImage(image, 64.0 / 2 + i * width, 64.0, width, 120.0);
              
            });
          
        }));
  
}

function renderScenesPlaceholder(ctx, size, editorContext) {
  var maxSceneWidth = calcMaxSceneWidth(size);
  clipOverTimeLineElement(ctx, 32, maxSceneWidth);
  Webapi__Canvas__Canvas2d.setFillStyle(ctx, /* String */0, "#9ca3af");
  ctx.fillRect(64.0 / 2.0, 64.0, maxSceneWidth, 120.0);
  
}

function renderCanvas(element, context) {
  var width = element.width;
  var height = element.height;
  console.log(width, height);
  
}

function renderTimeSlots(ctx, size, editorContext) {
  var maxSceneWidth = calcMaxSceneWidth(size);
  var stepsCount = Math.floor(Utils.$$Math.divideFloat(maxSceneWidth, 100)) | 0;
  var stepDuration = Caml_int32.div(editorContext.videoMeta.durationInFrames, stepsCount);
  return Belt_Range.forEach(0, stepsCount, (function (i) {
                var x = Math.imul(i, 100) + 64.0 / 2;
                ctx.beginPath();
                ctx.moveTo(x, 0);
                ctx.lineTo(x, 18);
                Webapi__Canvas__Canvas2d.setStrokeStyle(ctx, /* String */0, "#475569");
                ctx.stroke();
                if (i % 2 === 0) {
                  ctx.font = "12px sans-serif";
                  Webapi__Canvas__Canvas2d.setFillStyle(ctx, /* String */0, "#64748b");
                  ctx.fillText(Utils.Duration.formatSeconds(Utils.$$Math.divideFloat(Math.imul(i, stepDuration), editorContext.videoMeta.fps)), x + 8, 14, undefined);
                  return ;
                }
                
              }));
}

function Timeline(Props) {
  var sectionSize = Props.sectionSize;
  var canvasRef = React.useRef(null);
  var editorContext = EditorContext.useEditorContext(undefined);
  React.useEffect((function () {
          Belt_Option.map(Caml_option.nullable_to_opt(canvasRef.current), (function (element) {
                  var context = element.getContext("2d");
                  var scale = window.devicePixelRatio;
                  var scaledSize_height = sectionSize.height * scale;
                  var scaledSize_width = sectionSize.width * scale;
                  element.style.height = String(sectionSize.height) + "px";
                  element.style.width = String(sectionSize.width) + "px";
                  element.height = Math.floor(scaledSize_height) | 0;
                  element.width = Math.floor(scaledSize_width) | 0;
                  context.scale(scale, scale);
                  renderTimeSlots(context, sectionSize, editorContext);
                  var match = editorContext.editorState.playState;
                  if (match >= 3) {
                    renderScenesPlaceholder(context, sectionSize, editorContext);
                  } else {
                    renderMainScene(context, sectionSize, editorContext);
                  }
                  
                }));
          
        }), [sectionSize]);
  return React.createElement("canvas", {
              ref: canvasRef,
              height: String(Math.floor(sectionSize.height)) + "px",
              width: String(Math.floor(sectionSize.width)) + "px"
            });
}

var Canvas;

var Canvas2d;

var timeline_margin_x = 64.0;

var timeline_margin_y = 64.0;

var scene_height_size = 120.0;

var make = Timeline;

export {
  Canvas ,
  Canvas2d ,
  timeline_margin_x ,
  timeline_margin_y ,
  scene_height_size ,
  calcMaxSceneWidth ,
  renderRoundedRect ,
  clipOverTimeLineElement ,
  renderMainScene ,
  renderScenesPlaceholder ,
  renderCanvas ,
  renderTimeSlots ,
  make ,
  
}
/* react Not a pure module */
