// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as UseDimensions from "./useDimensions.bs.js";
import * as UseEditorLayout from "./useEditorLayout.bs.js";

function useEvent(fn) {
  var ref = React.useRef(fn);
  React.useLayoutEffect(function () {
        ref.current = fn;
        
      });
  return React.useCallback((function (arg) {
                return Curry._1(ref.current, arg);
              }), []);
}

var DocumentEvent = UseDimensions.DocumentEvent;

var getDimensions = UseDimensions.getDimensions;

var useDimensions = UseDimensions.useDimensions;

var min_timeline_height = UseEditorLayout.min_timeline_height;

var min_media_controls_width = UseEditorLayout.min_media_controls_width;

var sizeToStyle = UseEditorLayout.sizeToStyle;

var calculatePreviewSize = UseEditorLayout.calculatePreviewSize;

var useEditorLayout = UseEditorLayout.useEditorLayout;

export {
  DocumentEvent ,
  getDimensions ,
  useDimensions ,
  min_timeline_height ,
  min_media_controls_width ,
  sizeToStyle ,
  calculatePreviewSize ,
  useEditorLayout ,
  useEvent ,
  
}
/* react Not a pure module */
