// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml from "rescript/lib/es6/caml.js";
import * as EditorContext from "../EditorContext.bs.js";
import * as UseDimensions from "./useDimensions.bs.js";

function sizeToStyle(param) {
  return {
          height: String(param.height) + "px",
          width: String(param.width) + "px"
        };
}

function calculatePreviewSize(windowDimensions, param) {
  var height = param.height;
  var width = param.width;
  var max_preview_width = windowDimensions.width - 370 | 0;
  var max_preview_height = windowDimensions.height - 400 | 0;
  if (!(width > max_preview_width || height > max_preview_height)) {
    return {
            height: height,
            width: width,
            scale: 1.0
          };
  }
  var scale = Caml.caml_float_min(max_preview_width / width, max_preview_height / height);
  return {
          height: height * scale,
          width: width * scale,
          scale: scale
        };
}

function useEditorLayout(param) {
  var viewportSize = UseDimensions.useDimensions(undefined);
  var match = EditorContext.useEditorContext(undefined);
  var previewSize = calculatePreviewSize(viewportSize, match.videoMeta);
  return {
          timeLine: {
            height: viewportSize.height - previewSize.height,
            width: viewportSize.width,
            scale: 1.0
          },
          preview: previewSize,
          mediaControls: {
            height: previewSize.height,
            width: viewportSize.width - previewSize.width,
            scale: 1.0
          }
        };
}

var min_timeline_height = 400;

var min_media_controls_width = 370;

export {
  min_timeline_height ,
  min_media_controls_width ,
  sizeToStyle ,
  calculatePreviewSize ,
  useEditorLayout ,
  
}
/* EditorContext Not a pure module */
