// Generated by ReScript, PLEASE EDIT WITH CARE


var a = Math.random();

var RafRuntime = {
  a: a
};

var a$1 = Math.random();

var AudioContextRuntime = {
  a: a$1
};

function getModule(a) {
  if (a > 15) {
    return RafRuntime;
  } else {
    return AudioContextRuntime;
  }
}

export {
  RafRuntime ,
  AudioContextRuntime ,
  getModule ,
  
}
/* a Not a pure module */
