// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Utils from "../Utils.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as MediaLoader from "./mediaLoader.bs.js";
import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js";

var rafId = {
  contents: undefined
};

var playingSources = {
  contents: []
};

var startTime = {
  contents: 0
};

var lastFrameTime = {
  contents: undefined
};

var runtimeFps = {
  contents: undefined
};

var ctx = new AudioContext();

var gain = ctx.createGain();

function setVolume(value) {
  gain.gain.value = value;
  
}

function stop(param) {
  Belt_Option.map(rafId.contents, (function (prim) {
          cancelAnimationFrame(prim);
          
        }));
  return Belt_Array.forEach(playingSources.contents, (function (nameAndSource) {
                nameAndSource[1].stop();
                
              }));
}

function frame(onFrame, _timestamp) {
  var currentTime = ctx.currentTime;
  var thisFrameTime = Belt_Option.map(lastFrameTime.contents, (function (lastFrameTime) {
          return currentTime - lastFrameTime;
        }));
  var secondsFromStart = currentTime - startTime.contents;
  var match = runtimeFps.contents;
  var tmp;
  var exit = 0;
  if (match !== undefined) {
    if (thisFrameTime !== undefined) {
      if (thisFrameTime > 0) {
        tmp = match * 0.9 + 1 / thisFrameTime * (1 - 0.9);
      } else {
        exit = 1;
      }
    } else {
      tmp = undefined;
    }
  } else {
    exit = 1;
  }
  if (exit === 1) {
    tmp = thisFrameTime !== undefined && thisFrameTime > 0 ? 1 / thisFrameTime : undefined;
  }
  runtimeFps.contents = tmp;
  if (Curry._1(onFrame, secondsFromStart)) {
    lastFrameTime.contents = currentTime;
    rafId.contents = Caml_option.some(requestAnimationFrame(function (param) {
              return frame(onFrame, param);
            }));
    return ;
  } else {
    return stop(undefined);
  }
}

function connectAudioFiles(ctx, videoMeta) {
  var match = Curry._1(MediaLoader.MediaLoaderObserver.get, undefined);
  var mediaList = match.mediaList;
  console.log(videoMeta.audioMap);
  var map = videoMeta.audioMap;
  return Belt_Array.map(Belt_Array.keepMap((map == null) ? [] : Object.keys(map), (function (audioName) {
                    var media = Belt_MapString.getExn(mediaList, audioName);
                    switch (media.TAG | 0) {
                      case /* Media */1 :
                          var media$1 = media._0;
                          if (media$1.TAG === /* Audio */3) {
                            return [
                                    audioName,
                                    media$1._0
                                  ];
                          } else {
                            return ;
                          }
                      case /* Loading */0 :
                      case /* Error */2 :
                          return ;
                      
                    }
                  })), (function (res) {
                var source = ctx.createBufferSource();
                source.buffer = res[1].audioData;
                return [
                        res[0],
                        source
                      ];
              }));
}

function startAnimation(onFrame, currentFrame, videoMeta) {
  stop(undefined);
  playingSources.contents = connectAudioFiles(ctx, videoMeta);
  gain.connect(ctx.destination);
  startTime.contents = ctx.currentTime;
  Belt_Option.forEach(Caml_option.nullable_to_opt(videoMeta.audioMap), (function (audioMap) {
          return Belt_Array.forEach(playingSources.contents, (function (nameAndSource) {
                        var source = nameAndSource[1];
                        var match = Utils.$$Option.unwrap(audioMap[nameAndSource[0]]);
                        var endFrame = match[1];
                        var startFrame = match[0];
                        var offset = (currentFrame - startFrame | 0) / videoMeta.fps;
                        var duration = Math.max(startFrame > currentFrame ? ((endFrame - startFrame | 0) - currentFrame | 0) / videoMeta.fps : (endFrame - currentFrame | 0) / videoMeta.fps, 0);
                        source.connect(gain);
                        if (offset < 0) {
                          source.start(startTime.contents + Math.abs(offset), 0, duration);
                        } else {
                          source.start(startTime.contents, offset, duration);
                        }
                        
                      }));
        }));
  requestAnimationFrame(function (param) {
        return frame(onFrame, param);
      });
  
}

var AudioRuntime = {
  rafId: rafId,
  playingSources: playingSources,
  startTime: startTime,
  lastFrameTime: lastFrameTime,
  runtimeFps: runtimeFps,
  smoothing: 0.9,
  ctx: ctx,
  gain: gain,
  setVolume: setVolume,
  stop: stop,
  frame: frame,
  connectAudioFiles: connectAudioFiles,
  startAnimation: startAnimation
};

export {
  AudioRuntime ,
  
}
/* ctx Not a pure module */
