// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Utils from "../Utils.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as MediaLoader from "./mediaLoader.bs.js";
import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js";

var rafId = {
  contents: undefined
};

var playingSources = {
  contents: []
};

var audioContext = {
  contents: undefined
};

var startTime = {
  contents: 0
};

function frame(onFrame, _timestamp) {
  var secondsFromStart = Utils.$$Option.unwrap(audioContext.contents).currentTime - startTime.contents;
  if (Curry._1(onFrame, secondsFromStart)) {
    rafId.contents = Caml_option.some(requestAnimationFrame(function (param) {
              return frame(onFrame, param);
            }));
    return ;
  }
  
}

function connectAudioFiles(ctx, videoMeta) {
  var match = Curry._1(MediaLoader.MediaLoaderObserver.get, undefined);
  var mediaList = match.mediaList;
  return Belt_Array.map(Belt_Array.keepMap(Object.keys(Utils.$$Option.unwrap(videoMeta.audioMap)), (function (audioName) {
                    var media = Belt_MapString.getExn(mediaList, audioName);
                    switch (media.TAG | 0) {
                      case /* Media */1 :
                          var media$1 = media._0;
                          if (media$1.TAG === /* Audio */3) {
                            return [
                                    audioName,
                                    media$1._0
                                  ];
                          } else {
                            return ;
                          }
                      case /* Loading */0 :
                      case /* Error */2 :
                          return ;
                      
                    }
                  })), (function (res) {
                var source = ctx.createBufferSource();
                source.buffer = res[1].audioData;
                return [
                        res[0],
                        source
                      ];
              }));
}

function startAnimation(onFrame, currentFrame, videoMeta) {
  var ctx = new AudioContext();
  audioContext.contents = ctx;
  playingSources.contents = connectAudioFiles(ctx, videoMeta);
  var gain = ctx.createGain();
  gain.gain.value = 0.2;
  gain.connect(ctx.destination);
  startTime.contents = ctx.currentTime;
  Belt_Option.forEach(videoMeta.audioMap, (function (audioMap) {
          return Belt_Array.forEach(playingSources.contents, (function (nameAndSource) {
                        var source = nameAndSource[1];
                        var match = Utils.$$Option.unwrap(audioMap[nameAndSource[0]]);
                        var endFrame = match[1];
                        var startFrame = match[0];
                        var offset = (currentFrame - startFrame | 0) / videoMeta.fps;
                        var duration = Math.max(startFrame > currentFrame ? ((endFrame - startFrame | 0) - currentFrame | 0) / videoMeta.fps : (endFrame - currentFrame | 0) / videoMeta.fps, 0);
                        console.log(duration, offset);
                        source.connect(gain);
                        if (offset < 0) {
                          source.start(startTime.contents + Math.abs(offset), 0, duration);
                        } else {
                          source.start(startTime.contents, offset, duration);
                        }
                        
                      }));
        }));
  requestAnimationFrame(function (param) {
        return frame(onFrame, param);
      });
  
}

function stop(param) {
  Belt_Option.map(rafId.contents, (function (prim) {
          cancelAnimationFrame(prim);
          
        }));
  return Belt_Array.forEach(playingSources.contents, (function (nameAndSource) {
                var source = nameAndSource[1];
                console.log(source);
                source.stop();
                
              }));
}

var AudioRuntime = {
  rafId: rafId,
  playingSources: playingSources,
  audioContext: audioContext,
  startTime: startTime,
  frame: frame,
  connectAudioFiles: connectAudioFiles,
  startAnimation: startAnimation,
  stop: stop
};

export {
  AudioRuntime ,
  
}
/* MediaLoader Not a pure module */
