// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function makeMediaEditor(imports, name) {
  Belt_Option.map(Js_dict.get(imports, name), (function (val) {
          if (".mp3".endsWith(name)) {
            return 0;
          }
          throw {
                RE_EXN_ID: "Match_failure",
                _1: [
                  "mediaLoader.res",
                  15,
                  6
                ],
                Error: new Error()
              };
        }));
  
}

export {
  makeMediaEditor ,
  
}
/* No side effect */
