// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as MediaResolvers from "./MediaResolvers";

var resolveAudio = MediaResolvers.resolveAudio;

var resolveSubtitles = MediaResolvers.resolveSubtitles;

function processAudio(controller, imports) {
  return Belt_Array.keepMap(Object.entries(imports), (function (param) {
                var name = param[0];
                if (name.endsWith(".mp3")) {
                  return resolveAudio;
                } else if (name.endsWith(".vtt")) {
                  return resolveSubtitles;
                } else {
                  return ;
                }
              }));
}

export {
  resolveAudio ,
  resolveSubtitles ,
  processAudio ,
  
}
/* resolveAudio Not a pure module */
