// Generated by ReScript, PLEASE EDIT WITH CARE

import * as FontIcon from "./FontIcon";
import * as CaptionsIcon from "./CaptionsIcon";
import * as MusicalNoteIcon from "./MusicalNoteIcon";

var make = MusicalNoteIcon.MusicalNoteIcon;

var MusicalNotesIcon = {
  make: make
};

var make$1 = FontIcon.FontIcon;

var FontIcon$1 = {
  make: make$1
};

var make$2 = CaptionsIcon.CaptionsIcon;

var CaptionsIcon$1 = {
  make: make$2
};

export {
  MusicalNotesIcon ,
  FontIcon$1 as FontIcon,
  CaptionsIcon$1 as CaptionsIcon,
  
}
/* make Not a pure module */
