// Generated by ReScript, PLEASE EDIT WITH CARE


var $$Window = {};

var targetAsElement = (_ => _);

var $$Element = {
  targetAsElement: targetAsElement
};

var $$Float32Array = {};

export {
  $$Window ,
  $$Element ,
  $$Float32Array ,
  
}
/* No side effect */
