// Generated by ReScript, PLEASE EDIT WITH CARE


var $$AudioParam = {};

var $$AudioBuffer = {};

function setGainValue(gainNode, value, startTime) {
  gainNode.gain.setValueAtTime(value, startTime);
  
}

var $$Node = {
  setGainValue: setGainValue
};

var Context = {};

export {
  $$AudioParam ,
  $$AudioBuffer ,
  $$Node ,
  Context ,
  
}
/* No side effect */
