// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var editorContext = React.createContext(undefined);

var providerElement = editorContext.Provider;

function EditorContext$EditorContextProvider(Props) {
  var wasmController = Props.wasmController;
  var children = Props.children;
  return React.createElement(providerElement, {
              value: wasmController,
              children: children
            });
}

var EditorContextProvider = {
  providerElement: providerElement,
  make: EditorContext$EditorContextProvider
};

export {
  editorContext ,
  EditorContextProvider ,
  
}
/* editorContext Not a pure module */
