// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Hooks from "./hooks/Hooks.bs.js";
import * as React from "react";
import * as Timeline from "./Timeline/Timeline.bs.js";
import * as EditorContext from "./EditorContext.bs.js";
import * as UseEditorLayout from "./hooks/useEditorLayout.bs.js";

function last_from_array(arr) {
  return arr[arr.length - 1 | 0];
}

function Editor(Props) {
  var layout = Hooks.useEditorLayout(undefined);
  var context = EditorContext.useEditorContext(undefined);
  var name = last_from_array(context.videoMeta.name.split("::"));
  return React.createElement("div", {
              className: "w-screen h-screen bg-gray-900"
            }, React.createElement("div", {
                  className: "overflow-auto flex w-full"
                }, React.createElement("div", {
                      className: "col-span-2  h-full overflow-auto flex flex-col p-6",
                      style: UseEditorLayout.sizeToStyle(layout.mediaControls)
                    }, React.createElement("h1", {
                          className: "text-2xl font-medium text-white"
                        }, name !== undefined ? name : "Unknown video")), React.createElement("div", {
                      className: " bg-black",
                      style: UseEditorLayout.sizeToStyle(layout.preview)
                    })), React.createElement("div", {
                  className: "shadow-lg w-screen bg-gray-800",
                  style: UseEditorLayout.sizeToStyle(layout.timeLine)
                }, React.createElement(Timeline.make, {
                      sectionSize: layout.timeLine
                    })));
}

var make = Editor;

export {
  last_from_array ,
  make ,
  
}
/* Hooks Not a pure module */
