// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Timeline from "./Timeline/Timeline.bs.js";

function Editor(Props) {
  return React.createElement("div", {
              className: "w-screen h-screen bg-gray-900"
            }, React.createElement("div", {
                  className: "overflow-auto grid grid-cols-7 w-full h-2/3 "
                }, React.createElement("div", {
                      className: "col-span-2  h-full overflow-auto flex flex-col p-6"
                    }, React.createElement("h1", {
                          className: "text-4xl font-medium text-white"
                        }, "Test Video")), React.createElement("div", {
                      className: "col-span-5 bg-black"
                    })), React.createElement("div", {
                  className: "h-1/3 shadow-lg w-screen bg-gray-800"
                }, React.createElement(Timeline.make, {})));
}

var make = Editor;

export {
  make ,
  
}
/* react Not a pure module */
