// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Utils from "./Utils.bs.js";
import * as React from "react";
import * as Pervasives from "rescript/lib/es6/pervasives.js";
import * as MediaLoader from "./services/mediaLoader.bs.js";
import * as AnimationRuntime from "./services/AnimationRuntime.bs.js";
import * as Webapi__Dom__Window from "bs-webapi/src/Webapi/Dom/Webapi__Dom__Window.bs.js";
import * as Webapi__Dom__EventTarget from "bs-webapi/src/Webapi/Dom/Webapi__Dom__EventTarget.bs.js";

function editorReducer(state, action) {
  if (typeof action === "number") {
    switch (action) {
      case /* AllowPlay */0 :
          return {
                  frame: state.frame,
                  playState: /* WaitingForAction */2,
                  svg: state.svg,
                  wasmController: state.wasmController
                };
      case /* Play */1 :
          return {
                  frame: state.frame,
                  playState: /* Playing */0,
                  svg: state.svg,
                  wasmController: state.wasmController
                };
      case /* Pause */2 :
          return {
                  frame: state.frame,
                  playState: /* Paused */1,
                  svg: state.svg,
                  wasmController: state.wasmController
                };
      
    }
  } else {
    var indexOrDelta = action._0;
    var frame;
    frame = indexOrDelta.TAG === /* FrameIndex */0 ? indexOrDelta._0 : Math.round(indexOrDelta._0 * 60 / 1000) | 0;
    var svg = Curry._1(state.wasmController.render_frame, BigInt(frame));
    return {
            frame: frame,
            playState: state.playState,
            svg: svg,
            wasmController: state.wasmController
          };
  }
}

var DocumentEvent = Webapi__Dom__EventTarget.Impl({});

var editorContext = React.createContext(undefined);

function useEditorContext(param) {
  var context = React.useContext(editorContext);
  if (context !== undefined) {
    return context;
  } else {
    return Pervasives.failwith("Missing editorContext.");
  }
}

var providerElement = editorContext.Provider;

function getDefaultState(wasmController) {
  var state = Curry._1(MediaLoader.MediaLoaderObserver.get, undefined);
  if (state.allMediaLoaded) {
    return {
            frame: 0,
            playState: /* WaitingForAction */2,
            svg: Utils.$$Option.some(Curry._1(wasmController.render_frame, BigInt(0))),
            wasmController: wasmController
          };
  } else {
    return {
            frame: 0,
            playState: /* CantPlay */3,
            svg: undefined,
            wasmController: wasmController
          };
  }
}

function EditorContext$EditorContext(Props) {
  var wasmController = Props.wasmController;
  var videoMeta = Props.videoMeta;
  var children = Props.children;
  var match = React.useReducer(editorReducer, getDefaultState(wasmController));
  var dispatch = match[1];
  var editorState = match[0];
  React.useLayoutEffect((function () {
          return Curry._1(MediaLoader.MediaLoaderObserver.subscribe, (function (state) {
                        if (state.allMediaLoaded && editorState.playState === /* CantPlay */3) {
                          Curry._1(dispatch, /* AllowPlay */0);
                          return Curry._1(dispatch, /* NewFrame */{
                                      _0: {
                                        TAG: /* FrameIndex */0,
                                        _0: editorState.frame
                                      }
                                    });
                        }
                        
                      }));
        }), []);
  var onFrame = function (msDelta, fps) {
    Curry._1(dispatch, /* NewFrame */{
          _0: {
            TAG: /* DeltaTime */1,
            _0: msDelta
          }
        });
    
  };
  var start = React.useCallback((function (param) {
          Curry._1(dispatch, /* Play */1);
          return AnimationRuntime.RafAnimation.startAnimation(onFrame);
        }), [dispatch]);
  React.useEffect((function () {
          var handleKeydown = function (e) {
            console.log(editorState);
            var match = e.key;
            if (match === " ") {
              if (editorState.playState === /* Playing */0) {
                Curry._1(dispatch, /* Pause */2);
                return AnimationRuntime.RafAnimation.stop(undefined);
              } else {
                return Curry._1(start, undefined);
              }
            }
            
          };
          window.addEventListener("keydown", handleKeydown);
          return (function (param) {
                    window.removeEventListener("keydown", handleKeydown);
                    
                  });
        }), [editorState]);
  return React.createElement(providerElement, {
              value: {
                wasmController: wasmController,
                videoMeta: videoMeta,
                editorState: editorState
              },
              children: children
            });
}

var EditorContext = {
  providerElement: providerElement,
  getDefaultState: getDefaultState,
  make: EditorContext$EditorContext
};

export {
  editorReducer ,
  DocumentEvent ,
  editorContext ,
  useEditorContext ,
  EditorContext ,
  
}
/* DocumentEvent Not a pure module */
