// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function $$MediaList(Props) {
  return React.createElement("div", {
              className: "flex flex-col divide-y divide-gray-200"
            }, React.createElement("div", undefined));
}

var make = $$MediaList;

export {
  make ,
  
}
/* react Not a pure module */
