// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as EditorContext from "./EditorContext.bs.js";
import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js";

function MediaList$LoadedMedia(Props) {
  return React.createElement("div", undefined);
}

var LoadedMedia = {
  make: MediaList$LoadedMedia
};

function $$MediaList(Props) {
  var match = EditorContext.useEditorContext(undefined);
  var editorState = match.editorState;
  return React.createElement("ul", {
              className: "divide-y divide-gray-600"
            }, Belt_Array.map(Belt_MapString.keysToArray(editorState.mediaState), (function (name) {
                    var media = Belt_MapString.getExn(editorState.mediaState, name);
                    var tmp;
                    switch (media.TAG | 0) {
                      case /* Media */1 :
                          tmp = React.createElement(MediaList$LoadedMedia, {
                                media: media._0
                              });
                          break;
                      case /* Loading */0 :
                      case /* Error */2 :
                          tmp = "kekeker murokeke";
                          break;
                      
                    }
                    return React.createElement("li", {
                                className: "p-4"
                              }, tmp);
                  })));
}

var make = $$MediaList;

export {
  LoadedMedia ,
  make ,
  
}
/* react Not a pure module */
