// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Utils from "./Utils.bs.js";
import * as MediaLoader from "./services/mediaLoader.bs.js";
import * as UseObservable from "./hooks/useObservable.bs.js";
import * as AnimationRuntime from "./services/AnimationRuntime.bs.js";

function MakePlayer(Wasm) {
  var state = Curry._1(MediaLoader.MediaLoaderObserver.get, undefined);
  var initial = state.allMediaLoaded ? ({
        frame: 0,
        startPlayingFrame: 0,
        playState: /* WaitingForAction */2,
        svg: Utils.$$Option.some(Curry._1(Wasm.controller.render_frame, BigInt(0)))
      }) : ({
        frame: 0,
        startPlayingFrame: 0,
        playState: /* CantPlay */3,
        svg: undefined
      });
  var PlayerState = {
    initial: initial
  };
  var include = UseObservable.Pubsub(PlayerState);
  var get = include.get;
  var set = include.set;
  var reducer = function (action) {
    var state = Curry._1(get, undefined);
    if (typeof action === "number") {
      switch (action) {
        case /* AllowPlay */0 :
            return {
                    frame: state.frame,
                    startPlayingFrame: state.startPlayingFrame,
                    playState: /* WaitingForAction */2,
                    svg: state.svg
                  };
        case /* Play */1 :
            if (state.frame <= 0 || state.frame >= Wasm.videoMeta.durationInFrames) {
              return {
                      frame: 0,
                      startPlayingFrame: state.startPlayingFrame,
                      playState: /* Playing */0,
                      svg: state.svg
                    };
            } else {
              return {
                      frame: state.frame,
                      startPlayingFrame: state.frame,
                      playState: /* Playing */0,
                      svg: state.svg
                    };
            }
        case /* Pause */2 :
            return {
                    frame: state.frame,
                    startPlayingFrame: state.startPlayingFrame,
                    playState: /* Paused */1,
                    svg: state.svg
                  };
        
      }
    } else {
      var frame = action._0;
      if (frame === Wasm.videoMeta.durationInFrames) {
        var svg = Curry._1(Wasm.controller.render_frame, BigInt(frame));
        return {
                frame: frame,
                startPlayingFrame: state.startPlayingFrame,
                playState: /* Paused */1,
                svg: svg
              };
      }
      var svg$1 = Curry._1(Wasm.controller.render_frame, BigInt(frame));
      return {
              frame: frame,
              startPlayingFrame: state.startPlayingFrame,
              playState: state.playState,
              svg: svg$1
            };
    }
  };
  var sideEffect = function (action, dispatch) {
    if (typeof action !== "number") {
      return ;
    }
    switch (action) {
      case /* AllowPlay */0 :
          return ;
      case /* Play */1 :
          if (Curry._1(get, undefined).playState === /* Playing */0) {
            return ;
          }
          var onFrame = function (secondsFromStart) {
            var nextFrame = secondsFromStart * Wasm.videoMeta.fps + Curry._1(get, undefined).startPlayingFrame;
            Curry._1(dispatch, /* NewFrame */{
                  _0: Math.floor(nextFrame)
                });
            return Curry._1(get, undefined).playState === /* Playing */0;
          };
          AnimationRuntime.AudioRuntime.startAnimation(onFrame, Curry._1(get, undefined).frame, Wasm.videoMeta);
          return ;
      case /* Pause */2 :
          return AnimationRuntime.AudioRuntime.stop(undefined);
      
    }
  };
  var dispatch = function (action) {
    sideEffect(action, dispatch);
    return Curry._1(set, reducer(action));
  };
  return {
          PlayerState: PlayerState,
          mutableState: include.mutableState,
          listeners: include.listeners,
          get: get,
          set: set,
          nextId: include.nextId,
          subscribe: include.subscribe,
          useObservable: include.useObservable,
          reducer: reducer,
          sideEffect: sideEffect,
          dispatch: dispatch
        };
}

export {
  MakePlayer ,
  
}
/* MediaLoader Not a pure module */
