// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_int32 from "rescript/lib/es6/caml_int32.js";
import * as Pervasives from "rescript/lib/es6/pervasives.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function last(arr) {
  return arr[arr.length - 1 | 0];
}

function removeInPlace(arr, index) {
  return arr.splice(index, 1);
}

var $$Array = {
  last: last,
  removeInPlace: removeInPlace
};

function divideFloat(a, b) {
  return a / b;
}

var divideInt = Caml_int32.div;

function divideWithReminder(x, y) {
  return [
          Math.floor(x / y),
          x % y
        ];
}

var $$Math = {
  divideFloat: divideFloat,
  divideInt: divideInt,
  divideWithReminder: divideWithReminder
};

function unwrap(option) {
  if (option !== undefined) {
    return Caml_option.valFromOption(option);
  } else {
    return Pervasives.failwith("expect option to contain value");
  }
}

function unwrapOr(option, $$default) {
  if (option !== undefined) {
    return Caml_option.valFromOption(option);
  } else {
    return $$default;
  }
}

function some(val) {
  return Caml_option.some(val);
}

var $$Option = {
  unwrap: unwrap,
  unwrapOr: unwrapOr,
  some: some
};

function andReturn(a) {
  console.log(a);
  return a;
}

var Log = {
  andReturn: andReturn
};

function getFilename(path) {
  return path.replace(/^.*[\\/]/, "");
}

var Path = {
  getFilename: getFilename
};

function leftPad(n) {
  if (n > 9) {
    return n.toFixed(0);
  } else {
    return "0" + n.toFixed(0);
  }
}

function formatSeconds(seconds) {
  var match = divideWithReminder(seconds, 3600);
  var hours = match[0];
  var match$1 = divideWithReminder(match[1], 60);
  var seconds$1 = match$1[1];
  var minutes = match$1[0];
  if (hours > 1.0) {
    return leftPad(hours) + ":" + leftPad(minutes) + ":" + leftPad(seconds$1);
  } else {
    return leftPad(minutes) + ":" + leftPad(seconds$1);
  }
}

var Duration = {
  leftPad: leftPad,
  formatSeconds: formatSeconds
};

export {
  $$Array ,
  $$Math ,
  $$Option ,
  Log ,
  Path ,
  Duration ,
  
}
/* No side effect */
